### ISSUE TITLE
Some runs fail due to venv failing to activate

### ISSUE THREAD

**Issue by jcitrin** [duqtools/duqtools#366]
When testing a small UQ scan on the Gateway (9 cases), I've noticed that typically 1 or 2 of the cases fails to run, due to the following error:

![image](https://user-images.githubusercontent.com/6648646/195692909-eb0fef30-db03-441b-bd18-a718d3ed9c84.png)

The cases successfully launch when resubmitting them by hand. Likely the issue is due to a race condition and a process has a finite probability of trying to execute the activate script while it is still locked by another process.  

As a temporary workaround (since the issue might best be fixed on the JINTRAC side), perhaps the simplest thing to do for now is introduce a sleep command in the SLURM script?

**Comment by v1kko** [comment]
Its an interesting bug, and unfortunately one we can do little about, so we should at least create a bug report somewhere:
- [ ] Create bugreport with jintrac maintainers with the offending line number
       - The bug only exists because a venv is created to ensure mpi4py is installed, and only when running with more than 1 procesor, it could be assumed to be installed and no virtualenv would be needed.
I am not so sure about the workaround, especially since we cannot control exactly *when* a job starts, even if we submit it with a delay/sleep, that is entirely up to slurm to schedule. So our best bet might just be to resubmit failed jobs (we have `duqtools submit --resubmit run_xxxxx` now!)
- [ ] Workaround in duqtools?

**Comment by jcitrin** [comment]
Agree with the resubmit failed jobs solution. This can be automated as well
