### ISSUE TITLE
Check the quality of the normal distribution of the merge tool

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#440]
- [ ] Find a way to check the quality
- [ ] Find a way to report on the quality

**Comment by stefsmeets** [comment]
How do we define the quality of a normal distribution?

**Comment by stefsmeets** [comment]
We merge by calculating the mean and standard deviation along the runs axis. This may not give enough samples to do the normaltest ([scipy.stats.normaltest needs 20](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.normaltest.html)).

Since we want a single statistic for a data var, we should do the normaltest over the `runs`, `time` and `grid` dimensions.

To do so, we must calculate the mean and standard deviation as we do and then standardize the data:

$$\frac{X-\text{mean}(X)}{\text{std}(X)}$$

And then pass that to the normal test to do the significance test.

**Comment by stefsmeets** [comment]
This sort of works, but does not give a very satisfying answer. This is with 9 samples, and I think this is not enough to standardize the entire dataset. The distribution has two peaks around +-1 std, probably because there are not enough samples. 

```python
import matplotlib.pyplot as plt
from scipy import stats

...
data = ((ids_data['t_e'] - mean_data['t_e'])/ std_data['t_e'])
stats.normaltest(data.data.flatten())
>>> NormaltestResult(statistic=14331.000963376462, pvalue=0.0)
```

`pvalue = 0`, so the null hypothesis (= a normal distribution) *can* be rejected.

**Comment by stefsmeets** [comment]
Multivariate statistics:
https://pingouin-stats.org/
