### ISSUE TITLE
Make duqtools tools (plot,merge) compatible with local imasdb

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#486]
currently they work with public imasdb

**Comment by stefsmeets** [comment]
I'm wondering how this should work. Even in the `v220922` world, we still want to be able to grab data from the public imasdb. It is already compatible in the sense that you can set `user` to the absolute path for the local imasdb, but I think this will get awkward fast.

Just a couple of thoughts what this could look like. None of these make me very happy to be honest. 🤷

1. If we are in the jetto output directory, we could do something like this:

```bash
duqtools plot -h aug/12345/1 -h aug/12345/2 ...
```

Since we are already autogenerating the user if left blank, we could check if `imasdb` exists in the current directory and set that path as the user.

2. If we are in the duqtools run directory and we have access to `data.csv`. I think it's important that we are able to do the plotting from this directory, since this is where we initiate the runs.

Not sure what this interface would look like. In this case it would help if the entries in the data.csv have useful indices.

3. Simply add support for absolute or relative paths to the data, and then reconstruct the `user/db/shot/run` from there. Not super elegant, but quite explicit.

```bash
duqtools plot -p ./imasdb/aug/3/0/ids_xxx.datafile
```

**Comment by v1kko** [comment]
Can we differentiate between public and local by path? so public stays `-h g2vazizi/aug/123456/123` and local becomes: `-l <path>:<imashandle if there if more than 1>`

**Comment by v1kko** [comment]
That leaves the issue of the `data.csv`, but since that is `csv` we should be able to differentiate between a path and a user

**Comment by stefsmeets** [comment]
I think if we are are working with local imasdbs then `data.csv` should be written the full path in the user column.

**Comment by v1kko** [comment]
It is true, but I have one issue with absolute paths: We run into the limitation that we can not move the folder, and unfortunately executing things in docker usually moves things.

So I would suggest an extra path column, which, if empty just uses the public database, or if non empty determines the path to the local imasdb, this path can then also be relative.

**Comment by stefsmeets** [comment]
Do you also think we should code the path into `ImasHandler`?

i.e. have a new `imasdb_path` attribute and check for that instead of looking for the `'/'` prefix, which is a bit clumsy imo.
